## Feature Selection Techniques 
https://scikit-learn.org/stable/user_guide.html

https://scikit-learn.org/stable/modules/feature_selection.html

- involves selecting a subset of the most informative features from the original set to improve estimators’ accuracy scores or to boost their performance on very high-dimensional datasets.

### 1. Removing features with low variance
<p><i>VarianceThreshold</i> is a simple baseline approach to feature selection. It removes all features whose variance doesn’t meet some threshold. By default, it removes all zero-variance features, i.e. features that have the same value in all samples.

In [3]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer

In [4]:
cancer = load_breast_cancer()
X_cancer = pd.DataFrame(data=cancer.data,columns=cancer.feature_names)
y_cancer = pd.Series(data=cancer.target, name='class') # Target
cancer_df=pd.concat([X_cancer,y_cancer],axis=1)
cancer_df.sample(5)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,class
335,17.06,21.00,111.80,918.6,0.11190,0.10560,0.15080,0.09934,0.1727,0.06071,...,33.15,143.20,1362.0,0.14490,0.2053,0.39200,0.18270,0.2623,0.07599,0
420,11.57,19.04,74.20,409.7,0.08546,0.07722,0.05485,0.01428,0.2031,0.06267,...,26.98,86.43,520.5,0.12490,0.1937,0.25600,0.06664,0.3035,0.08284,1
48,12.05,14.63,78.04,449.3,0.10310,0.09092,0.06592,0.02749,0.1675,0.06043,...,20.70,89.88,582.6,0.14940,0.2156,0.30500,0.06548,0.2747,0.08301,1
305,11.60,24.49,74.23,417.2,0.07474,0.05688,0.01974,0.01313,0.1935,0.05878,...,31.62,81.39,476.5,0.09545,0.1361,0.07239,0.04815,0.3244,0.06745,1
128,15.10,16.39,99.58,674.5,0.11500,0.18070,0.11380,0.08534,0.2001,0.06467,...,18.33,105.90,762.6,0.13860,0.2883,0.19600,0.14230,0.2590,0.07779,1

In [5]:
cancer_df['class'].value_counts()

class
1    357
0    212
Name: count, dtype: int64

#### Using <code>class sklearn.feature_selection.VarianceThreshold(threshold=0.0)

In [7]:
import numpy as np
from sklearn.feature_selection import VarianceThreshold

X = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 1], [0, 1, 1], [0, 1, 0], [0, 1, 1]])
print(X)
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
sel.fit_transform(X)

[[0 0 1]
 [0 1 0]
 [1 0 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]]

array([[0, 1],
       [1, 0],
       [0, 1],
       [1, 1],
       [1, 0],
       [1, 1]])

In [8]:
.8 * (1 - .8)

0.15999999999999998

In [9]:
5/6

0.8333333333333334

In [10]:
X

array([[0, 0, 1],
       [0, 1, 0],
       [1, 0, 1],
       [0, 1, 1],
       [0, 1, 0],
       [0, 1, 1]])

In [11]:
X[:,0].var()

0.13888888888888892

VarianceThreshold has removed the first column, which has a probability p= 5/6 > 0.8 of containing a zero.
<hr>

#### Trying the VarianceThreshold on breast cancer dataset

In [14]:
X_cancer_new=sel.fit_transform(X_cancer)
X_cancer_new

array([[  17.99,   10.38,  122.8 , ...,   17.33,  184.6 , 2019.  ],
       [  20.57,   17.77,  132.9 , ...,   23.41,  158.8 , 1956.  ],
       [  19.69,   21.25,  130.  , ...,   25.53,  152.5 , 1709.  ],
       ...,
       [  16.6 ,   28.08,  108.3 , ...,   34.12,  126.7 , 1124.  ],
       [  20.6 ,   29.33,  140.1 , ...,   39.42,  184.6 , 1821.  ],
       [   7.76,   24.54,   47.92, ...,   30.37,   59.16,  268.6 ]])

In [15]:
sel.get_support()

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False, False])

In [16]:
selected_features=X_cancer.columns[sel.get_support()]
selected_features.values

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'texture error', 'perimeter error', 'area error', 'worst radius',
       'worst texture', 'worst perimeter', 'worst area'], dtype=object)

In [17]:
X_cancer.columns.values #original set of columns

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype=object)

In [18]:
removed_features=X_cancer.columns[~sel.get_support()]
removed_features.values

array(['mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'smoothness error', 'compactness error',
       'concavity error', 'concave points error', 'symmetry error',
       'fractal dimension error', 'worst smoothness', 'worst compactness',
       'worst concavity', 'worst concave points', 'worst symmetry',
       'worst fractal dimension'], dtype=object)

In [19]:
X_cancer[selected_features].var()

mean radius            12.418920
mean texture           18.498909
mean perimeter        590.440480
mean area          123843.554318
texture error           0.304316
perimeter error         4.087896
area error           2069.431583
worst radius           23.360224
worst texture          37.776483
worst perimeter      1129.130847
worst area         324167.385102
dtype: float64

In [20]:
X_cancer[removed_features].var()

mean smoothness            0.000198
mean compactness           0.002789
mean concavity             0.006355
mean concave points        0.001506
mean symmetry              0.000752
mean fractal dimension     0.000050
radius error               0.076902
smoothness error           0.000009
compactness error          0.000321
concavity error            0.000911
concave points error       0.000038
symmetry error             0.000068
fractal dimension error    0.000007
worst smoothness           0.000521
worst compactness          0.024755
worst concavity            0.043524
worst concave points       0.004321
worst symmetry             0.003828
worst fractal dimension    0.000326
dtype: float64

### 2.Univariate Selection

selects the best features based on univariate statistical tests.

- <b>SelectKBest</b> removes all but the highest scoring features
<br><code>class sklearn.feature_selection.SelectKBest(score_func=<function f_classif>, *, k=10)</code>
- <b>SelectPercentile</b> removes all but a user-specified highest scoring percentage of features 
- using common univariate statistical tests for each feature: false positive rate <b>SelectFpr</b>,  false discovery rate <b>SelectFdr </b>, or family wise error SelectFwe.
- <b>GenericUnivariateSelect</b> allows to perform univariate feature selection with a configurable strategy. This allows to select the best univariate selection strategy with hyper-parameter search estimator.

In [22]:
from sklearn.feature_selection import SelectKBest,SelectPercentile,RFE,chi2
from sklearn.feature_selection import f_classif
from sklearn.svm import SVC,SVR

#### Using the SelectKBest

In [24]:
selector=SelectKBest(f_classif, k=5)
X_new = selector.fit_transform(X_cancer, y_cancer)
X_new.shape

(569, 5)

In [25]:
kselected_features=X_cancer.columns[selector.get_support()]
kselected_features.values

array(['mean perimeter', 'mean concave points', 'worst radius',
       'worst perimeter', 'worst concave points'], dtype=object)

In [26]:
removed_features=X_cancer.columns[~selector.get_support()]
removed_features.values

array(['mean radius', 'mean texture', 'mean area', 'mean smoothness',
       'mean compactness', 'mean concavity', 'mean symmetry',
       'mean fractal dimension', 'radius error', 'texture error',
       'perimeter error', 'area error', 'smoothness error',
       'compactness error', 'concavity error', 'concave points error',
       'symmetry error', 'fractal dimension error', 'worst texture',
       'worst area', 'worst smoothness', 'worst compactness',
       'worst concavity', 'worst symmetry', 'worst fractal dimension'],
      dtype=object)

#### Using the SelectPercentile

In [28]:
selector=SelectPercentile(chi2, percentile=25)
X_new = selector.fit_transform(X_cancer, y_cancer)
X_new.shape

(569, 8)

In [29]:
selected_features=X_cancer.columns[selector.get_support()]
selected_features.values

array(['mean radius', 'mean perimeter', 'mean area', 'perimeter error',
       'area error', 'worst radius', 'worst perimeter', 'worst area'],
      dtype=object)

In [30]:
removed_features=X_cancer.columns[~selector.get_support()]
removed_features.values

array(['mean texture', 'mean smoothness', 'mean compactness',
       'mean concavity', 'mean concave points', 'mean symmetry',
       'mean fractal dimension', 'radius error', 'texture error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst texture', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype=object)

### 3. Recursive Feature Elimination

Selects features by recursively considering smaller and smaller sets of features. First, the estimator is trained on the initial set of features and the importance of each feature is obtained either through any specific attribute. Then the least important features are pruned from current set of features. That procedure is recursively repeated on the pruned set until the desired number of features to select is eventually reached.

In [32]:
svc = SVC(kernel="linear", C=1)
selector = RFE(estimator=svc, n_features_to_select=10, step=1)
selector.fit(X_cancer, y_cancer)
selector

RFE(estimator=SVC(C=1, kernel='linear'), n_features_to_select=10)

In [33]:
X_cancer.columns.tolist()

['mean radius',
 'mean texture',
 'mean perimeter',
 'mean area',
 'mean smoothness',
 'mean compactness',
 'mean concavity',
 'mean concave points',
 'mean symmetry',
 'mean fractal dimension',
 'radius error',
 'texture error',
 'perimeter error',
 'area error',
 'smoothness error',
 'compactness error',
 'concavity error',
 'concave points error',
 'symmetry error',
 'fractal dimension error',
 'worst radius',
 'worst texture',
 'worst perimeter',
 'worst area',
 'worst smoothness',
 'worst compactness',
 'worst concavity',
 'worst concave points',
 'worst symmetry',
 'worst fractal dimension']

In [34]:
selector.ranking_

array([ 1, 12,  7, 21,  4,  3,  1,  1,  2, 18, 16,  1,  5, 13, 14, 10,  9,
       11, 19, 17,  1,  6, 15, 20,  1,  1,  1,  1,  1,  8])

In [35]:
cancer_selected_features=X_cancer.columns[selector.get_support()]
cancer_selected_features.values

array(['mean radius', 'mean concavity', 'mean concave points',
       'texture error', 'worst radius', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry'], dtype=object)

#### RFE on boston dataset

In [37]:
boston_df=pd.read_csv('data/boston.csv')
boston_df.head()

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [38]:
X_boston=boston_df.iloc[:,1:-1]
y_boston=boston_df['medv']
X_boston.head(3)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03

In [39]:
y_boston.unique()

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 13.6, 19.6, 15.2, 14.5,
       15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 13.2, 13.1, 13.5, 20. ,
       24.7, 30.8, 34.9, 26.6, 25.3, 21.2, 19.3, 14.4, 19.4, 19.7, 20.5,
       25. , 23.4, 35.4, 31.6, 23.3, 18.7, 16. , 22.2, 33. , 23.5, 22. ,
       17.4, 20.9, 24.2, 22.8, 24.1, 21.4, 20.8, 20.3, 28. , 23.9, 24.8,
       22.5, 23.6, 22.6, 20.6, 28.4, 38.7, 43.8, 33.2, 27.5, 26.5, 18.6,
       20.1, 19.5, 19.8, 18.8, 18.5, 18.3, 19.2, 17.3, 15.7, 16.2, 18. ,
       14.3, 23. , 18.1, 17.1, 13.3, 17.8, 14. , 13.4, 11.8, 13.8, 14.6,
       15.4, 21.5, 15.3, 17. , 41.3, 24.3, 27. , 50. , 22.7, 23.8, 22.3,
       19.1, 29.4, 23.2, 24.6, 29.9, 37.2, 39.8, 37.9, 32.5, 26.4, 29.6,
       32. , 29.8, 37. , 30.5, 36.4, 31.1, 29.1, 33.3, 30.3, 34.6, 32.9,
       42.3, 48.5, 24.4, 22.4, 28.1, 23.7, 26.7, 30.1, 44.8, 37.6, 46.7,
       31.5, 31.7, 41.7, 48.3, 29. , 25.1, 17.6, 24.5, 26.2, 42.8, 21.9,
       44. , 36. , 33.8, 43.1, 48.8, 31. , 36.5, 30.7, 43.5, 20.7, 21.1,
       25.2, 35.2, 32.4, 33.1, 35.1, 45.4, 46. , 32.2, 28.5, 37.3, 27.9,
       28.6, 36.1, 28.2, 16.1, 22.1, 19. , 32.7, 31.2, 17.2, 16.8, 10.2,
       10.4, 10.9, 11.3, 12.3,  8.8,  7.2, 10.5,  7.4, 11.5, 15.1,  9.7,
       12.5,  8.5,  5. ,  6.3,  5.6, 12.1,  8.3, 11.9, 17.9, 16.3,  7. ,
        7.5,  8.4, 16.7, 14.2, 11.7, 11. ,  9.5, 14.1,  9.6,  8.7, 12.8,
       10.8, 14.9, 12.6, 13. , 16.4, 17.7, 12. , 21.8,  8.1])

In [40]:
svr = SVR(kernel="linear", C=1)
selector = RFE(estimator=svr, n_features_to_select=5, step=1)
selector.fit(X_boston, y_boston)
selector

RFE(estimator=SVR(C=1, kernel='linear'), n_features_to_select=5)

In [41]:
boston_features=X_boston.columns[selector.get_support()]
boston_features.values

array(['chas', 'nox', 'rm', 'ptratio', 'lstat'], dtype=object)

## __Hyperparameter  Tuning__

In machine learning, we have two types of parameters: _those that are learned from the training data, for example, the weights in logistic regression, and the parameters of a learning algorithm that are optimized separately_. The latter are the tuning parameters, also called _hyperparameters_, of a model, for example, the regularization parameter in logistic regression or the depth parameter of a decision tree. The hyperparameters are configuration variables which cannot be directly learned from the regular training process. These are typically set before the actual training process begins and control aspects of the learning process itself. They influence the model’s performance, its complexity and how fast it learns.

__Hyperparameter tuning__ is the process of selecting the optimal values for a machine learning model’s hyperparameters.  The two best strategies for Hyperparameter tuning are ___GridSearchCV___ and ___RandomizedSearchCV___.

The approach of grid search is quite simple, it's a brute-force exhaustive search paradigm where we specify a list of values for different hyperparameters, and the computer evaluates the model performance for each combination of those to obtain the optimal set. Below is an example of using GridSearchCV

In [44]:
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV,LearningCurveDisplay,train_test_split
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error
import numpy as np
from mlxtend.evaluate import bias_variance_decomp

In [45]:
X_boston.shape

(506, 13)

In [46]:
# Load dataset
X_train, X_test, y_train, y_test = train_test_split(X_boston, y_boston, test_size=0.2, random_state=42)

In [47]:
#define all possible parameters for the different models
models = [
    {
        'name': 'Ridge Regression',
        'estimator': Pipeline([
            ('scaler', StandardScaler()),
            ('ridge', Ridge())
        ]),
        'params': {
            'ridge__alpha': [0.1, 1.0, 10.0],
            'ridge__fit_intercept': [True, False]
        }
    },
    {
        'name': 'Decision Tree',
        'estimator': DecisionTreeRegressor(),
        'params': {
            'max_depth': [None, 5, 10],
            'min_samples_split': [2, 5],
        }
    },
    {
        'name': 'Random Forest',
        'estimator': RandomForestRegressor(random_state=42),
        'params': {
            'n_estimators': [50, 100],
            'max_depth': [None, 10],
            'min_samples_split': [2, 5],
        }
    },
    {
        'name': 'SVR',
        'estimator': Pipeline([
            ('scaler', StandardScaler()),
            ('svr', SVR())
        ]),
        'params': {
            'svr__kernel': ['linear', 'rbf'],
            'svr__C': [0.1, 1.0, 10.0],
            'svr__epsilon': [0.1, 0.2],
        }
    },
    {
        'name': 'Linear Regression',
        'estimator': Pipeline([
            ('scaler', StandardScaler()),
            ('lr', LinearRegression())
        ]),
        'params': {
            'lr__fit_intercept': [True, False],
            'lr__positive': [True, False],
            'lr__n_jobs': [-1, 1]
        }
    },
]

In [48]:
import warnings
warnings.filterwarnings("ignore")
best_models=[]
print("🔍 Running GridSearchCV and RandomizedSearchCV...\n")
for model in models:
    print(f"📌 {model['name']}")
    
    # Grid Search
    grid = GridSearchCV(estimator=model['estimator'], param_grid=model['params'],
                        cv=5, scoring='neg_mean_squared_error', n_jobs=-1)
    grid.fit(X_train, y_train)
    y_pred = grid.predict(X_test)
    rmse = mean_squared_error(y_test, y_pred, squared=False)
    r2=r2_score(y_test,y_pred)
    best_models.append({'name':model['name']+'_grid', 'model':grid.best_estimator_,'best_params':grid.best_params_})
    print(f"🔹 GridSearchCV Best Params: {grid.best_params_}")
    print(f"🔹 GridSearchCV RMSE: {rmse:.4f}")
    print(f"🔹 GridSearchCV r2: {r2:.4f}")
    
    # Random Search
    random = RandomizedSearchCV(estimator=model['estimator'], param_distributions=model['params'],
                                n_iter=5, cv=5, scoring='neg_mean_squared_error', n_jobs=-1, random_state=42)
    random.fit(X_train, y_train)
    y_pred_r = random.predict(X_test)
    rmse_r = mean_squared_error(y_test, y_pred_r, squared=False)
    r2=r2_score(y_test,y_pred)
    best_models.append({'name':model['name']+'_rand', 'model':random.best_estimator_,'best_params':random.best_params_})
    print(f"🔸 RandomSearchCV Best Params: {random.best_params_}")
    print(f"🔸 RandomSearchCV RMSE: {rmse_r:.4f}")
    print(f"🔸 RandomSearchCV r2: {r2:.4f}\n")
    best_models

🔍 Running GridSearchCV and RandomizedSearchCV...

📌 Ridge Regression
🔹 GridSearchCV Best Params: {'ridge__alpha': 1.0, 'ridge__fit_intercept': True}
🔹 GridSearchCV RMSE: 4.9308
🔹 GridSearchCV r2: 0.6685
🔸 RandomSearchCV Best Params: {'ridge__fit_intercept': True, 'ridge__alpha': 1.0}
🔸 RandomSearchCV RMSE: 4.9308
🔸 RandomSearchCV r2: 0.6685

📌 Decision Tree
🔹 GridSearchCV Best Params: {'max_depth': None, 'min_samples_split': 2}
🔹 GridSearchCV RMSE: 4.7705
🔹 GridSearchCV r2: 0.6897
🔸 RandomSearchCV Best Params: {'min_samples_split': 2, 'max_depth': 10}
🔸 RandomSearchCV RMSE: 4.1903
🔸 RandomSearchCV r2: 0.6897

📌 Random Forest
🔹 GridSearchCV Best Params: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 100}
🔹 GridSearchCV RMSE: 2.8110
🔹 GridSearchCV r2: 0.8923
🔸 RandomSearchCV Best Params: {'n_estimators': 100, 'min_samples_split': 2, 'max_depth': None}
🔸 RandomSearchCV RMSE: 2.8110
🔸 RandomSearchCV r2: 0.8923

📌 SVR
🔹 GridSearchCV Best Params: {'svr__C': 10.0, 'svr__epsilon': 0.2, 'svr__kernel': 'rbf'}
🔹 GridSearchCV RMSE: 3.5530
🔹 GridSearchCV r2: 0.8279
🔸 RandomSearchCV Best Params: {'svr__kernel': 'rbf', 'svr__epsilon': 0.1, 'svr__C': 10.0}
🔸 RandomSearchCV RMSE: 3.5691
🔸 RandomSearchCV r2: 0.8279

📌 Linear Regression
🔹 GridSearchCV Best Params: {'lr__fit_intercept': True, 'lr__n_jobs': -1, 'lr__positive': False}
🔹 GridSearchCV RMSE: 4.9286
🔹 GridSearchCV r2: 0.6688
🔸 RandomSearchCV Best Params: {'lr__positive': False, 'lr__n_jobs': -1, 'lr__fit_intercept': True}
🔸 RandomSearchCV RMSE: 4.9286
🔸 RandomSearchCV r2: 0.6688

In [49]:
print(best_models)

[{'name': 'Ridge Regression_grid', 'model': Pipeline(steps=[('scaler', StandardScaler()), ('ridge', Ridge())]), 'best_params': {'ridge__alpha': 1.0, 'ridge__fit_intercept': True}}, {'name': 'Ridge Regression_rand', 'model': Pipeline(steps=[('scaler', StandardScaler()), ('ridge', Ridge())]), 'best_params': {'ridge__fit_intercept': True, 'ridge__alpha': 1.0}}, {'name': 'Decision Tree_grid', 'model': DecisionTreeRegressor(), 'best_params': {'max_depth': None, 'min_samples_split': 2}}, {'name': 'Decision Tree_rand', 'model': DecisionTreeRegressor(max_depth=10), 'best_params': {'min_samples_split': 2, 'max_depth': 10}}, {'name': 'Random Forest_grid', 'model': RandomForestRegressor(random_state=42), 'best_params': {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 100}}, {'name': 'Random Forest_rand', 'model': RandomForestRegressor(random_state=42), 'best_params': {'n_estimators': 100, 'min_samples_split': 2, 'max_depth': None}}, {'name': 'SVR_grid', 'model': Pipeline(steps=[('scaler', StandardScaler()),
                ('svr', SVR(C=10.0, epsilon=0.2))]), 'best_params': {'svr__C': 10.0, 'svr__epsilon': 0.2, 'svr__kernel': 'rbf'}}, {'name': 'SVR_rand', 'model': Pipeline(steps=[('scaler', StandardScaler()), ('svr', SVR(C=10.0))]), 'best_params': {'svr__kernel': 'rbf', 'svr__epsilon': 0.1, 'svr__C': 10.0}}, {'name': 'Linear Regression_grid', 'model': Pipeline(steps=[('scaler', StandardScaler()),
                ('lr', LinearRegression(n_jobs=-1))]), 'best_params': {'lr__fit_intercept': True, 'lr__n_jobs': -1, 'lr__positive': False}}, {'name': 'Linear Regression_rand', 'model': Pipeline(steps=[('scaler', StandardScaler()),
                ('lr', LinearRegression(n_jobs=-1))]), 'best_params': {'lr__positive': False, 'lr__n_jobs': -1, 'lr__fit_intercept': True}}]

In [ ]:
results = []

for model_dict in best_models:
    name = model_dict['name']
    model = model_dict['model']
    #model.fit(X_train, y_train) #don't need to refit or retrain  since GridSearchCV and RandomSearchCV already fit the parameters
    mse, bias, variance = bias_variance_decomp(model, np.array(X_train), np.array(y_train), np.array(X_test), np.array(y_test), loss='mse', num_rounds=200, random_seed=4)
    y_pred = model.predict(X_test)
    r2 = r2_score(y_test, y_pred)
    mae =mean_absolute_error(y_test, y_pred)
    rmse = mean_squared_error(y_test, y_pred,squared=False)
    results.append((name, r2,mae,mse,rmse, bias,variance))
    print(results,'\n')

[('Ridge Regression_grid', 0.6683972740559108, 3.2543530482712857, 25.295152284342038, 4.931296219023538, 24.32230375160743, 0.9728485327345935)]

[('Ridge Regression_grid', 0.6683972740559108, 3.2543530482712857, 25.295152284342038, 4.931296219023538, 24.32230375160743, 0.9728485327345935), ('Ridge Regression_rand', 0.6683972740559108, 3.2543530482712857, 25.295152284342038, 4.931296219023538, 24.32230375160743, 0.9728485327345935)]

[('Ridge Regression_grid', 0.6683972740559108, 3.2543530482712857, 25.295152284342038, 4.931296219023538, 24.32230375160743, 0.9728485327345935), ('Ridge Regression_rand', 0.6683972740559108, 3.2543530482712857, 25.295152284342038, 4.931296219023538, 24.32230375160743, 0.9728485327345935), ('Decision Tree_grid', 0.6894363969771182, 3.336274509803922, 22.29655784313725, 4.772295456231585, 9.811006431372546, 12.485551411764705)]

[('Ridge Regression_grid', 0.6683972740559108, 3.2543530482712857, 25.295152284342038, 4.931296219023538, 24.32230375160743, 0.9728485327345935), ('Ridge Regression_rand', 0.6683972740559108, 3.2543530482712857, 25.295152284342038, 4.931296219023538, 24.32230375160743, 0.9728485327345935), ('Decision Tree_grid', 0.6894363969771182, 3.336274509803922, 22.29655784313725, 4.772295456231585, 9.811006431372546, 12.485551411764705), ('Decision Tree_rand', 0.6111757460565006, 3.515419948128928, 22.362962770180758, 5.339845833558019, 9.877426169007904, 12.485536601172864)]

In [ ]:
results_df = pd.DataFrame(results, columns=['Model', 'R-Squared','MAE','MSE','RMSE','Bias','Variance'])
results_df

In [ ]:
import matplotlib.pyplot as plt
for model_dict in best_models:
    name = model_dict['name']
    model = model_dict['model']
    params=model_dict['best_params']
    print(name,params)
    display=LearningCurveDisplay.from_estimator(model, X_train, y_train, train_sizes=np.linspace(0.1, 1.0, 5), cv=5)
    display.ax_.set_title(f"Learning Curve: {name}")
    plt.show()

In [ ]:
results_df