In [1]:
import pandas as pd

In [8]:
df=pd.read_csv('dataset/titanic2.csv')
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [10]:
df.shape

(1310, 14)

In [11]:
df.dtypes

pclass       float64
survived     float64
name             str
sex              str
age          float64
sibsp        float64
parch        float64
ticket           str
fare         float64
cabin            str
embarked         str
boat             str
body         float64
home.dest        str
dtype: object

In [12]:
df.isna().sum()

pclass          1
survived        1
name            1
sex             1
age           264
sibsp           1
parch           1
ticket          1
fare            2
cabin        1015
embarked        3
boat          824
body         1189
home.dest     565
dtype: int64

In [13]:
features=df.iloc[:,:-1].columns
features

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body'],
      dtype='str')

In [14]:
target='survived'

In [15]:
len(df)

1310

In [16]:
train=df.sample(int(len(df)*.8))
print(train.shape)
train.head()

(1048, 14)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
816,3.0,0.0,"Gheorgheff, Mr. Stanio",male,NaN,0.0,0.0,349254,7.8958,NaN,C,NaN,NaN,NaN
955,3.0,0.0,"Lefebre, Miss. Ida",female,NaN,3.0,1.0,4133,25.4667,NaN,S,NaN,NaN,NaN
1285,3.0,0.0,"Wenzel, Mr. Linhart",male,32.5,0.0,0.0,345775,9.5000,NaN,S,NaN,298.0,NaN
106,1.0,0.0,"Farthing, Mr. John",male,NaN,0.0,0.0,PC 17483,221.7792,C95,S,NaN,NaN,NaN
1153,3.0,0.0,"Robins, Mrs. Alexander A (Grace Charity Laury)",female,47.0,1.0,0.0,A/5. 3337,14.5000,NaN,S,NaN,7.0,NaN

In [17]:
test=df.drop(index=train.index)
print(test.shape)
test.head()

(262, 14)

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
13,1.0,1.0,"Barber, Miss. Ellen ""Nellie""",female,26.0,0.0,0.0,19877,78.8500,NaN,S,6,NaN,NaN
15,1.0,0.0,"Baumann, Mr. John D",male,NaN,0.0,0.0,PC 17318,25.9250,NaN,S,NaN,NaN,"New York, NY"
20,1.0,1.0,"Beckwith, Mr. Richard Leonard",male,37.0,1.0,1.0,11751,52.5542,D35,S,5,NaN,"New York, NY"
22,1.0,1.0,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30.0000,C148,C,5,NaN,"New York, NY"
23,1.0,1.0,"Bidois, Miss. Rosalie",female,42.0,0.0,0.0,PC 17757,227.5250,NaN,C,4,NaN,NaN

In [19]:
from sklearn.model_selection import train_test_split
train,test=train_test_split(df,test_size=0.2, random_state=42)
print(train.shape)
print(test.shape)

(1048, 14)
(262, 14)

In [20]:
print(train.head())
test.head()

     pclass  survived                                               name  \
199     1.0       1.0   Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")
303     1.0       0.0                           Warren, Mr. Frank Manley
481     2.0       1.0  Laroche, Mrs. Joseph (Juliette Marie Louise La...
331     2.0       0.0                           Bailey, Mr. Percy Andrew
10      1.0       0.0                             Astor, Col. John Jacob

        sex   age  sibsp  parch         ticket      fare    cabin embarked  \
199  female  24.0    0.0    0.0       PC 17482   49.5042      C90        C
303    male  64.0    1.0    0.0         110813   75.2500      D37        C
481  female  22.0    1.0    2.0  SC/Paris 2123   41.5792      NaN        C
331    male  18.0    0.0    0.0          29108   11.5000      NaN        S
10     male  47.0    1.0    0.0       PC 17757  227.5250  C62 C64        C

    boat   body                       home.dest
199    6    NaN           Belgium  Montreal, PQ
303  NaN    NaN                    Portland, OR
481   14    NaN                   Paris / Haiti
331  NaN    NaN  Penzance, Cornwall / Akron, OH
10   NaN  124.0                    New York, NY

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
701,3.0,0.0,"Calic, Mr. Petar",male,17.0,0.0,0.0,315086,8.6625,NaN,S,NaN,NaN,NaN
994,3.0,0.0,"Mardirosian, Mr. Sarkis",male,NaN,0.0,0.0,2655,7.2292,F E46,C,NaN,NaN,NaN
350,2.0,1.0,"Brown, Miss. Edith Eileen",female,15.0,0.0,2.0,29750,39.0000,NaN,S,14,NaN,"Cape Town, South Africa / Seattle, WA"
986,3.0,0.0,"Maenpaa, Mr. Matti Alexanteri",male,22.0,0.0,0.0,STON/O 2. 3101275,7.1250,NaN,S,NaN,NaN,NaN
409,2.0,0.0,"Fox, Mr. Stanley Hubert",male,36.0,0.0,0.0,229236,13.0000,NaN,S,NaN,236.0,"Rochester, NY"

In [21]:
train.survived.value_counts()

survived
0.0    659
1.0    388
Name: count, dtype: int64

In [22]:
test.survived.value_counts()

survived
0.0    150
1.0    112
Name: count, dtype: int64

In [23]:
df.survived.value_counts()

survived
0.0    809
1.0    500
Name: count, dtype: int64

In [25]:
382/500

0.764

In [26]:
665/809

0.8220024721878862

In [28]:
df_clean = df.dropna(subset=['survived']) 
train_df, test_df = train_test_split(
    df_clean, 
    test_size=0.2, 
    random_state=42, 
    stratify=df_clean.survived
)

In [29]:
train_df.survived.value_counts()

survived
0.0    647
1.0    400
Name: count, dtype: int64

In [30]:
test_df.survived.value_counts()

survived
0.0    162
1.0    100
Name: count, dtype: int64

In [31]:
df.survived.value_counts()

survived
0.0    809
1.0    500
Name: count, dtype: int64

In [32]:
400/500

0.8

In [33]:
809*.8

647.2

In [34]:
809-647

162

In [35]:
train_df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
999,3.0,1.0,"McCarthy, Miss. Catherine ""Katie""",female,NaN,0.0,0.0,383123,7.7500,NaN,Q,15 16,NaN,NaN
392,2.0,1.0,"del Carlo, Mrs. Sebastiano (Argenia Genovesi)",female,24.0,1.0,0.0,SC/PARIS 2167,27.7208,NaN,C,12,NaN,"Lucca, Italy / California"
628,3.0,0.0,"Andersson, Miss. Sigrid Elisabeth",female,11.0,4.0,2.0,347082,31.2750,NaN,S,NaN,NaN,"Sweden Winnipeg, MN"
1165,3.0,0.0,"Saad, Mr. Khalil",male,25.0,0.0,0.0,2672,7.2250,NaN,C,NaN,NaN,NaN
604,3.0,1.0,"Abelseth, Miss. Karen Marie",female,16.0,0.0,0.0,348125,7.6500,NaN,S,16,NaN,"Norway Los Angeles, CA"

In [36]:
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import cross_val_score,KFold
from sklearn.metrics import confusion_matrix, accuracy_score

In [37]:
X_train=train_df[features]
y_train=train_df[target]
X_test=test_df[features]
y_test=test_df[target]

In [38]:
X_test.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body
1028,3.0,1.0,"Moran, Miss. Bertha",female,NaN,1.0,0.0,371110,24.1500,NaN,Q,16,NaN
1121,3.0,1.0,"Peter, Master. Michael J",male,NaN,1.0,1.0,2668,22.3583,NaN,C,C,NaN
1155,3.0,0.0,"Rommetvedt, Mr. Knud Paust",male,NaN,0.0,0.0,312993,7.7750,NaN,S,NaN,NaN
1251,3.0,0.0,"Tomlin, Mr. Ernest Portage",male,30.5,0.0,0.0,364499,8.0500,NaN,S,NaN,50.0
721,3.0,0.0,"Coleff, Mr. Peju",male,36.0,0.0,0.0,349210,7.4958,NaN,S,NaN,NaN

In [39]:
svcmodel=SVC(kernel='linear')
CARTModel=DecisionTreeClassifier()

In [ ]:
 
cols_to_drop = ['Name', 'Ticket', 'Cabin', 'PassengerId', 'survived']
X = df.drop(columns=cols_to_drop) 
X = pd.get_dummies(X, drop_first=True) 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42) 
svcmodel.fit(X_train, y_train)

ValueError: could not convert string to float: 'McCarthy, Miss. Catherine "Katie"'